package com.kara4k.tutor18.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kara4k.tutor18.model.Event;
import com.kara4k.tutor18.model.Lesson;
import com.kara4k.tutor18.model.Person;

import com.kara4k.tutor18.model.EventDao;
import com.kara4k.tutor18.model.LessonDao;
import com.kara4k.tutor18.model.PersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig lessonDaoConfig;
    private final DaoConfig personDaoConfig;

    private final EventDao eventDao;
    private final LessonDao lessonDao;
    private final PersonDao personDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(Lesson.class, lessonDao);
        registerDao(Person.class, personDao);
    }
    
    public void clear() {
        eventDaoConfig.clearIdentityScope();
        lessonDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
