package com.kara4k.tutor18.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "events".
*/
public class EventDao extends AbstractDao<Event, Long> {

    public static final String TABLENAME = "events";

    /**
     * Properties of entity Event.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PersonId = new Property(1, Long.class, "personId", false, "PERSON_ID");
        public final static Property LessonId = new Property(2, Long.class, "lessonId", false, "LESSON_ID");
        public final static Property State = new Property(3, int.class, "state", false, "STATE");
        public final static Property RescheduledToId = new Property(4, Long.class, "rescheduledToId", false, "RESCHEDULED_TO_ID");
        public final static Property RescheduledFromId = new Property(5, Long.class, "rescheduledFromId", false, "RESCHEDULED_FROM_ID");
        public final static Property IsPayment = new Property(6, boolean.class, "isPayment", false, "IS_PAYMENT");
        public final static Property IsPaid = new Property(7, boolean.class, "isPaid", false, "IS_PAID");
        public final static Property ExpectedPrice = new Property(8, double.class, "expectedPrice", false, "EXPECTED_PRICE");
        public final static Property Price = new Property(9, double.class, "price", false, "PRICE");
        public final static Property Subjects = new Property(10, String.class, "subjects", false, "SUBJECTS");
        public final static Property Note = new Property(11, String.class, "note", false, "NOTE");
    }

    private DaoSession daoSession;


    public EventDao(DaoConfig config) {
        super(config);
    }
    
    public EventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"events\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PERSON_ID\" INTEGER," + // 1: personId
                "\"LESSON_ID\" INTEGER," + // 2: lessonId
                "\"STATE\" INTEGER NOT NULL ," + // 3: state
                "\"RESCHEDULED_TO_ID\" INTEGER," + // 4: rescheduledToId
                "\"RESCHEDULED_FROM_ID\" INTEGER," + // 5: rescheduledFromId
                "\"IS_PAYMENT\" INTEGER NOT NULL ," + // 6: isPayment
                "\"IS_PAID\" INTEGER NOT NULL ," + // 7: isPaid
                "\"EXPECTED_PRICE\" REAL NOT NULL ," + // 8: expectedPrice
                "\"PRICE\" REAL NOT NULL ," + // 9: price
                "\"SUBJECTS\" TEXT," + // 10: subjects
                "\"NOTE\" TEXT);"); // 11: note
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"events\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Event entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long personId = entity.getPersonId();
        if (personId != null) {
            stmt.bindLong(2, personId);
        }
 
        Long lessonId = entity.getLessonId();
        if (lessonId != null) {
            stmt.bindLong(3, lessonId);
        }
        stmt.bindLong(4, entity.getState());
 
        Long rescheduledToId = entity.getRescheduledToId();
        if (rescheduledToId != null) {
            stmt.bindLong(5, rescheduledToId);
        }
 
        Long rescheduledFromId = entity.getRescheduledFromId();
        if (rescheduledFromId != null) {
            stmt.bindLong(6, rescheduledFromId);
        }
        stmt.bindLong(7, entity.getIsPayment() ? 1L: 0L);
        stmt.bindLong(8, entity.getIsPaid() ? 1L: 0L);
        stmt.bindDouble(9, entity.getExpectedPrice());
        stmt.bindDouble(10, entity.getPrice());
 
        String subjects = entity.getSubjects();
        if (subjects != null) {
            stmt.bindString(11, subjects);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(12, note);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Event entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long personId = entity.getPersonId();
        if (personId != null) {
            stmt.bindLong(2, personId);
        }
 
        Long lessonId = entity.getLessonId();
        if (lessonId != null) {
            stmt.bindLong(3, lessonId);
        }
        stmt.bindLong(4, entity.getState());
 
        Long rescheduledToId = entity.getRescheduledToId();
        if (rescheduledToId != null) {
            stmt.bindLong(5, rescheduledToId);
        }
 
        Long rescheduledFromId = entity.getRescheduledFromId();
        if (rescheduledFromId != null) {
            stmt.bindLong(6, rescheduledFromId);
        }
        stmt.bindLong(7, entity.getIsPayment() ? 1L: 0L);
        stmt.bindLong(8, entity.getIsPaid() ? 1L: 0L);
        stmt.bindDouble(9, entity.getExpectedPrice());
        stmt.bindDouble(10, entity.getPrice());
 
        String subjects = entity.getSubjects();
        if (subjects != null) {
            stmt.bindString(11, subjects);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(12, note);
        }
    }

    @Override
    protected final void attachEntity(Event entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Event readEntity(Cursor cursor, int offset) {
        Event entity = new Event( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // personId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // lessonId
            cursor.getInt(offset + 3), // state
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // rescheduledToId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // rescheduledFromId
            cursor.getShort(offset + 6) != 0, // isPayment
            cursor.getShort(offset + 7) != 0, // isPaid
            cursor.getDouble(offset + 8), // expectedPrice
            cursor.getDouble(offset + 9), // price
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // subjects
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // note
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Event entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPersonId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLessonId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setState(cursor.getInt(offset + 3));
        entity.setRescheduledToId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setRescheduledFromId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setIsPayment(cursor.getShort(offset + 6) != 0);
        entity.setIsPaid(cursor.getShort(offset + 7) != 0);
        entity.setExpectedPrice(cursor.getDouble(offset + 8));
        entity.setPrice(cursor.getDouble(offset + 9));
        entity.setSubjects(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setNote(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Event entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Event entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Event entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPersonDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLessonDao().getAllColumns());
            builder.append(" FROM events T");
            builder.append(" LEFT JOIN persons T0 ON T.\"PERSON_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN lessons T1 ON T.\"LESSON_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Event loadCurrentDeep(Cursor cursor, boolean lock) {
        Event entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Person person = loadCurrentOther(daoSession.getPersonDao(), cursor, offset);
        entity.setPerson(person);
        offset += daoSession.getPersonDao().getAllColumns().length;

        Lesson lesson = loadCurrentOther(daoSession.getLessonDao(), cursor, offset);
        entity.setLesson(lesson);

        return entity;    
    }

    public Event loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Event> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Event> list = new ArrayList<Event>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Event> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Event> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
